### ISSUE TITLE
different run result

### ISSUE THREAD

**Issue by IrMK42** [hemanth1403/Driver-Assistance-System#1]
I don't know why, when running, the source code has an incorrect path for reading warning and prompt. More importantly, the running effect is completely different from what you showed, and there is no code for detecting human eyes.

**Comment by hemanth1403** [comment]
Hey! 

1. Path has to be changed accordingly to the user 
2. I have shown the integration of drowsiness detection and other claimed functionalities via hardware i.e. the device will have 2 perspectives one for the road and the other for the driver.  For drowsiness detection, we detect human eyes by using facial landmarks and it is there in the Drowsiness Detector directory. 

I hope you have a great day.
Thank you.
